version: '3.8'

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${DB_USERNAME_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - backend

  library_db:
    image: postgres:15
    container_name: library_db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: ${DB_USERNAME_LIBRARY}
      POSTGRES_PASSWORD: ${DB_PASSWORD_LIBRARY}
    ports:
      - "5433:5432"
    volumes:
      - library_db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  auth_db_data:
  redis_data:
  library_db_data:

networks:
  backend: