package com.ahicode.storage.enums;

public enum BookGenre {
    FICTION_FANTASY_GENRE,
    FICTION_DETECTIVES_GENRE,
    FICTION_HORRORS_GENRE,
    FICTION_ADVENTURES_GENRE,
    FICTION_POETRY_GENRE,
    FICTION_ROMANCE_NOVELS_GENRE,
    FICTION_THRILLERS_GENRE,
    FICTION_COMICS_AND_MANGA_GENRE,
    NOT_FICTION_BUSINESS_LITERATURE_GENRE,
    NOT_FICTION_PSYCHOLOGY_GENRE,
    NOT_FICTION_ARTS_AND_CULTURE_GENRE,
    NOT_FICTION_SCIENTIFIC_GENRE,
    NOT_FICTION_COMPUTER_SCIENCE_GENRE,
    NOT_FICTION_HISTORICAL_GENRE,
    NOT_FICTION_SOCIETY_GENRE,
    NOT_FICTION_MEMOIRS_GENRE,
    NOT_FICTION_PHILOSOPHY_GENRE,
    NOT_FICTION_RELIGION_GENRE;
}
